import { slugify } from './slugify';

// Single source of truth for courses used by the UI and dynamic pages.
export const allCourses = [
  {
    id: 1,
    title: 'Certification in JavaScript Development',
    author: 'IIDAD Academy',
    rating: 4.6,
    ratingsCount: '1,240',
    duration: 3,
    tags: [],
    img: '/courseThumbnail/certification/java%20script%203%20months.png',
    description:
      'A compact certification covering core JavaScript concepts, DOM manipulation, and modern tooling for building interactive web experiences.',
  },
  {
    id: 2,
    title: 'Certification in CSS Development',
    author: 'IIDAD Academy',
    rating: 4.5,
    ratingsCount: '980',
    duration: 4,
    tags: [],
    img: '/courseThumbnail/certification/CSS%20DEVELOPMENT%203%20months.png',
    description:
      'Practical CSS course covering layouts, responsive design, modern CSS features and component-based styling approaches.',
  },
  {
    id: 3,
    title: 'Advanced Frontend Development course',
    author: 'IIDAD Academy',
    rating: 4.7,
    ratingsCount: '2,100',
    duration: 6,
    tags: ['Bestseller'],
    img: '/courseThumbnail/advanced/frontend%206%20months.png',
    description: 'A deep dive into modern frontend engineering: frameworks, performance, and scalable architectures.',
  },
  {
    id: 4,
    title: 'Advanced Backend Development course',
    author: 'IIDAD Academy',
    rating: 4.6,
    ratingsCount: '1,750',
    duration: 6,
    tags: [],
    img: '/courseThumbnail/advanced/BACKEND%206%20months.png',
    description: 'Back-end systems, APIs, databases and deployment practices for production applications.',
  },
  {
    id: 5,
    title: 'Advanced Mobile App Development course',
    author: 'IIDAD Academy',
    rating: 4.6,
    ratingsCount: '1,430',
    duration: 6,
    tags: [],
    img: '/courseThumbnail/advanced/Mobile%20app%20development%206%20months.png',
    description: 'Build cross-platform mobile apps using modern toolchains and UX best practices.',
  },
  {
    id: 6,
    title: 'Advanced QA Testing Certification course',
    author: 'IIDAD Academy',
    rating: 4.5,
    ratingsCount: '860',
    duration: 6,
    tags: [],
    img: '/courseThumbnail/advanced/QA%20TESTING%20CERTIFICATION%206%20months.png',
    description: 'Testing strategies, automation, and quality practices to ship reliable software.',
  },
  {
    id: 7,
    title: 'Advanced React & Redux course',
    author: 'IIDAD Academy',
    rating: 4.8,
    ratingsCount: '2,540',
    duration: 6,
    tags: ['Bestseller'],
    img: '/courseThumbnail/advanced/React%20%26%20Redux%206%20months.png',
    description: 'Advanced patterns in React, state management, and performance optimization.',
  },
  {
    id: 8,
    title: 'Diploma in Frontend Development',
    author: 'IIDAD Academy',
    rating: 4.7,
    ratingsCount: '3,120',
    duration: 12,
    tags: [],
    img: '/courseThumbnail/diploma/FRONTEND%20DEVELOPMENT%2012months.png',
    description: 'A year-long diploma that prepares you for a career as a frontend developer.',
  },
  {
    id: 9,
    title: 'Diploma in JavaScript Algorithms',
    author: 'IIDAD Academy',
    rating: 4.6,
    ratingsCount: '1,900',
    duration: 12,
    tags: [],
    img: '/courseThumbnail/diploma/JAVASCRIPT%20ALGORITHMS%2012months.png',
    description: 'Algorithmic thinking and JavaScript-focused algorithm study for interviews and problem solving.',
  },
  {
    id: 10,
    title: 'Diploma in Fullstack Development',
    author: 'IIDAD Academy',
    rating: 4.7,
    ratingsCount: '2,800',
    duration: 12,
    tags: ['Bestseller'],
    img: '/courseThumbnail/diploma/FULLSTACK%20DEVELOPMENT%2012months.png',
    description: 'Fullstack curriculum covering frontend, backend, databases and cloud deployment.',
  },
  {
    id: 11,
    title: 'Certification in Animations in 3.js',
    author: 'IIDAD Academy',
    rating: 4.4,
    ratingsCount: '420',
    duration: 3,
    tags: [],
    img: '/courseThumbnail/certification/three.js.png',
    description: 'Create web animations and interactive visualizations using three.js.',
  },
  {
    id: 12,
    title: 'Diploma in Backend Development',
    author: 'IIDAD Academy',
    rating: 4.6,
    ratingsCount: '1,750',
    duration: 12,
    tags: [],
    img: '/images/course-placeholder.png',
    description: 'Comprehensive backend diploma focused on reliability, APIs and data modeling.',
  },
  {
    id: 13,
    title: 'Diploma in Fullstack Development with Generative AI',
    author: 'IIDAD Academy',
    rating: 4.8,
    ratingsCount: '3,400',
    duration: 12,
    tags: ['Bestseller'],
    img: '/courseThumbnail/diploma/FULLSTACK%20DEVELOPMENT%20with%20gen%20ai%2012months.png',
    description: 'Fullstack development infused with generative AI modules and practical projects.',
  },
];

// attach slug to each course for convenience
export const getAllCourses = () =>
  allCourses.map((c) => ({ ...c, slug: slugify(c.title) }));

export const getCourseBySlug = (slug) => getAllCourses().find((c) => c.slug === slug);

export default {
  allCourses,
  getAllCourses,
  getCourseBySlug,
};
